name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Añadimos MongoDB para que 'npm test' funcione
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x # Fijamos una versión para ir más rápido
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - run: npm ci

      - name: Prettier Check
        run: npm run format:check

      - name: ESLint Check
        run: npm run lint

      - name: TypeScript Type Check
        run: npm run check

      # --- PASO DE BUILD ---
      - name: Build project
        run: npm run build

      # --- PASO DE TESTS CON VARIABLE DE ENTORNO Pública ---
      - name: Run Tests
        env:
          MONGO_URI: mongodb://localhost:27017/test_db
        run: npm test
